server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh            #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #lb协议
          predicates:
            - Path=/payment/get/**     #断言,路径相匹配的进行路由
            - Method=GET
            - Before=2023-03-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Cookie=username,atguigu    #并且Cookie是username=atguigu才能访问
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由
#            - Host=**.atguigu.com

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**      #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka